Add offline broadcasting pages
Granola-Team/mina-block-explorer pull request #210
Opened 2024-01-24 17:52 UTC by n1tranquilla

2024-01-24 22:08 UTC, n1tranquilla commented
Please merge #206 first

2024-01-26 13:17 UTC, trevorbernard requested changes

2024-01-26 13:17 UTC, trevorbernard commented on .github/CODEOWNERS
> +* @n1tranquilla @robinbb @Isaac-DeFrain
Leave me in the CODEOWNERS

2024-01-26 13:17 UTC, trevorbernard commented on Justfile
> +  echo cargo audit
Remove the echo

2024-01-26 14:21 UTC, trevorbernard approved these changes

2024-01-26 14:21 UTC, merged