Issue 885
Granola-Team/mina-block-explorer pull request #893
Opened 2024-06-22 17:39 UTC by n1tranquilla

Closes #885

2024-06-22 17:41 UTC, n1tranquilla commented
@robinbb same as the others. We can merge whenever.

2024-06-22 19:13 UTC, trevorbernard commented on src/user_commands/table_trait.rs
> +                        convert_to_pill("Not Applied".to_string(), ColorVariant::Orange)
This should be "Failed"

2024-06-22 19:20 UTC, robinbb requested changes
"Failed" is the official name for transactions that were not applied, it seems.

2024-06-23 04:53 UTC, robinbb approved these changes

2024-06-23 04:53 UTC, merged